spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.198.174:33066/red_jinggangshan?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: "123456"

  redis:
    host: 124.221.198.174
    port: 6379
    database: 0
server:
  port: 8080
#  ssl:
#    key-store: classpath:abmy.online.pfx
#    key-store-password: h4rhvdvz405yf6